use single info point that is extendable
OwnWeb/map_elevation pull request #2
Opened 2020-08-18 08:51 UTC by moovida

New PR to reflect minimal changes as discussed in previous PR.

2020-08-18 11:29 UTC, tuarrep requested changes

2020-08-18 11:29 UTC, tuarrep commented on lib/map_elevation.dart
> +  final ElevationPoint elevationPoint;
BC here. Just let it named `position`

2020-08-18 11:29 UTC, tuarrep commented on lib/map_elevation.dart
> -  lg.LatLng latLng;
Please add a getter for backward compatibility to retrieve an instance of `LatLng` (basically `this`)

2020-08-18 12:26 UTC, moovida commented
@tuarrep added the requested changes. Thanks for reviewing.

2020-08-18 12:46 UTC, tuarrep approved these changes
LGTM

2020-08-19 07:04 UTC, HugoHeneault submitted a review, later dismissed
Hi! Cool PR. Thanks a lot!

Could you remove `import 'package:latlong/latlong.dart';` from `example/data.dart`? It is now unused.

With that change, LGTM 👍 

Thanks

2020-08-19 07:09 UTC, tuarrep requested changes
Could you please rebase on master too. We've added some CI

2020-08-19 09:09 UTC, moovida commented
Import removed and rebase done. Thanks guys!

2020-08-19 09:17 UTC, tuarrep approved these changes

2020-08-19 09:18 UTC, merged